version: '3'

services:
  varonka:
    build:
      context: .
    environment:
      - VARONKA_GREETINGS=/tmp/varonka/greetings.edn
    ports:
      - "10927:10927"
    volumes:
      - ${PWD}/default-greetings.edn:/tmp/varonka/greetings.edn
