version: '3'

services:
  varonka:
    build:
      context: .
    environment:
      - VARONKA_NICK=varonka-dev
      - VARONKA_GREETINGS=/tmp/varonka/greetings.edn
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/default-greetings.edn:/tmp/varonka/greetings.edn
